version: "3"

services:
  node-app:
    build: .
    environment:
      - PORT=3000
    deploy:
      replicas: 3
    networks:
      - app-network

  envoy:
    image: envoyproxy/envoy:v1.26-latest
    ports:
      - "80:80"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml:ro
    depends_on:
      - node-app
    networks:
      - app-network

networks:
  app-network:
