http:
  port: 8080

apiEndpoints:
  default:
    host: "*"
    paths: "/api/*"

serviceEndpoints:
  node-api:
    url: "http://node-api:3000"

policies:
  - proxy

pipelines:
  default:
    apiEndpoints:
      - default
    policies:
      - proxy:
          - action:
              serviceEndpoint: node-api
