version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - node-api
    networks:
      - nginx-net

  node-api:
    build: ./node-api
    networks:
      - nginx-net

networks:
  nginx-net:
    driver: bridge
