version: "3.8"
services:
  app1:
    build: .
    ports:
      - "3001:3000"

  app2:
    build: .
    ports:
      - "3002:3000"

  app3:
    build: .
    ports:
      - "3003:3000"

  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
