version: "3.8"

services:
  express-gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - node-api
    networks:
      - express-gw-net

  node-api:
    build: ./node-api
    networks:
      - express-gw-net

networks:
  express-gw-net:
    driver: bridge
